### ISSUE TITLE
Many ideas

### ISSUE THREAD

**Issue by pidgeon777** [vinsworldcom/nppTagLEET#3]
Hello, I've many ideas which would improve this plugin a lot.

Would it be ok if I post them here? Just for your evaluation or eventually as a reminder for those who might be interested in keeping the development of this plugin active by forking it.

**Comment by vinsworldcom** [comment]
Sure.  I may not be able to do anything if they are too ambitious - I'm not a good C++ coder nor is this my code.

The actual author (@gstavi) maintains https://sourceforge.net/projects/tagleet/ and https://github.com/gstavi/npp/tree/master/tagleet.  As long as the current developer (@gstavi) is active, I won't be release this as other than a "pre-release" so as not to step on the current Notepad++ Plugin Admin version.  If you want to see changes in the Plugins Admin version, you should post issues on the two aforementioned links.

Cheers.

**Comment by pidgeon777** [comment]
I had a look at your links and it seems that the latest plugin version has been released on 2018-06-03. It seems the original author doesn't maintain it anymore.

I'll start creating some threads here eventually as suggestions for those willing to fork the project or as reminders for me, if I'll fork this project in the upcoming weeks/months, also.

I'm not a C++ coder, though, so I should start learning it before doing any fork. We'll see.
